<b class="footer-titles  text-myriad-pro-regular-16  black-757575">Pages</b>

	<!--<div class="product-tags">
		<b class="footer-titles  text-myriad-pro-regular-16  black-757575">Pages</b>
		<div class="text-sourse-sans-pro-regular-14  grey-a0a0a0">
			<ul>
				<li>Home</li>
				<li>About us</li>
				<li>Contacts info</li>
				<li>Guarantees</li>
				<li>Promotions</li>
				<li>Work with us</li>
				<li>For Suppliers</li>
				<?php /*echo $this->getChildHtml('schon.footer.cmspageslinks.container'); */?>
			</ul>
		</div>
	</div>-->
