<!--<h2>Custom search</h2>-->


<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper(\Magento\Search\Helper\Data::class);
?>


<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
    <svg width="20" height="20" viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg">
        <path d="M1216 832q0-185-131.5-316.5t-316.5-131.5-316.5 131.5-131.5 316.5 131.5 316.5 316.5 131.5 316.5-131.5 131.5-316.5zm512 832q0 52-38 90t-90 38q-54 0-90-38l-343-342q-179 124-399 124-143 0-273.5-55.5t-225-150-150-225-55.5-273.5 55.5-273.5 150-225 225-150 273.5-55.5 273.5 55.5 225 150 150 225 55.5 273.5q0 220-124 399l343 343q37 37 37 90z" />
    </svg>
    <svg width="20" height="20" viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg">
        <path d="M1395 736q0 13-10 23l-466 466q-10 10-23 10t-23-10l-466-466q-10-10-10-23t10-23l50-50q10-10 23-10t23 10l393 393 393-393q10-10 23-10t23 10l50 50q10 10 10 23z"></path>
    </svg>
</a>
<div class="dropdown-menu  dropdown-search-wrapper">
    <div class="row">
        <div class="col-sm-8  col-sm-offset-2">

            <form class="form minisearch  form-horizontal" id="search_mini_form" action="<?= /* @escapeNotVerified */ $helper->getResultUrl() ?>" method="get">
                <div class="field search  form-group">
                    <div class="control  col-xs-11  dropdown-search__input-wrapper">
                        <input id="search" class="form-control  dropdown-search__input  forms-input  grey-f0f0f0-bg  text-source-sans-pro-light-14  placeholder-color-909090"
                               data-mage-init='{"quickSearch":{
                                "formSelector":"#search_mini_form",
                                "url":"<?= /* @escapeNotVerified */ $helper->getSuggestUrl()?>",
                                "destinationSelector":"#search_autocomplete"}
                           }'
                               type="text"
                               name="<?= /* @escapeNotVerified */ $helper->getQueryParamName() ?>"
                               value="<?= /* @escapeNotVerified */ $helper->getEscapedQueryText() ?>"
                               placeholder="<?= /* @escapeNotVerified */ __('Search entire store here...') ?>"
                               maxlength="<?= /* @escapeNotVerified */ $helper->getMaxQueryLength() ?>"
                               role="combobox"
                               aria-haspopup="false"
                               aria-autocomplete="both"
                               autocomplete="off"/>
                        <div id="search_autocomplete" class="search-autocomplete"></div>
				        <?= $block->getChildHtml() ?>
                    </div>
                    <div class="col-xs-1">
                        <button type="submit" class="dropdown-search__button  dropdown-search__button-search  transparent-button">
                            <svg width="20" height="20" viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg">
                                <path d="M1216 832q0-185-131.5-316.5t-316.5-131.5-316.5 131.5-131.5 316.5 131.5 316.5 316.5 131.5 316.5-131.5 131.5-316.5zm512 832q0 52-38 90t-90 38q-54 0-90-38l-343-342q-179 124-399 124-143 0-273.5-55.5t-225-150-150-225-55.5-273.5 55.5-273.5 150-225 225-150 273.5-55.5 273.5 55.5 225 150 150 225 55.5 273.5q0 220-124 399l343 343q37 37 37 90z" />
                            </svg>
                        </button>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>


