<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top  dropdown clearfix', 'submenu  dropdown-menu products-lists__dropdown-menu', $columnsLimit) ?>

<nav class="navigation  schon-test-label" data-action="navigation">
    <ul class="nav navbar-nav  navbar-right  main-menu" >
        <?= /* @escapeNotVerified */ $_menu ?>
        <?= /* @escapeNotVerified */ $block->getChildHtml() ?>
    </ul>
</nav>


<?php //var_dump($block->getChildHtml()); ?>

<!--dropdown clearfix  pull-left-->
